#!/bin/sh

PATH_OHMYZSH='/usr/share/zsh/ohmyzsh'
PATH_PURE='/usr/share/zsh/themes/pure'
PATH_GOLANG='/opt/go'
PATH_DOCKER_SECRET_SERVICE='/usr/bin/docker-credential-secretservice'

PATH_I3_CONFIG='HOME/.config/i3/config'
PATH_I3_STATUS_CONFIG='HOME/.config/i3status/config'
PATH_I3_SCRIPTS='HOME/.config/i3/scripts'
PATH_PICOM_CONFIG='/etc/xdg/picom.conf'
PATH_VIM_CONFIG='HOME/.vimrc'
PATH_VIM_PROFILE='/etc/profile.d/vim.sh'
PATH_VIM_DIR='HOME/.vim'
PATH_KITTY_CONFIG='HOME/.config/kitty/kitty.conf'
PATH_KITTY_PROFILE='/etc/profile.d/kitty.sh'
PATH_XORG_TOUCHPAD_CONFIG='/etc/X11/xorg.conf.d/30-touchpad.conf'
PATH_DOCKER_CONFIG='HOME/.docker/config.json'
PATH_GO_PROFILE='/etc/profile.d/go.sh'
PATH_SSH_CONFIG='HOME/.ssh/ssh_agent.sh'
PATH_LY_CONFIG='/etc/ly/config.ini'
PATH_ZSH_CONFIG='HOME/.zshrc'
PATH_NOTIFICATION_DAEMON_CONFIG='/usr/share/dbus-1/services/org.freedesktop.Notifications.service'
