# This is a basic workflow to help you get started with Actions

name: Trigger updates

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  trigger_updates:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Trigger config-files ref update for os-setup
        env:
          TOKEN_WORKFLOW_DISPATCH: "${{ secrets.TOKEN_WORKFLOW_DISPATCH }}"
        run: |
          curl -H 'Accept: application/vnd.github.v3+json' \
          -H "Authorization: Bearer ${TOKEN_WORKFLOW_DISPATCH}"
          -X POST \
          -d '{ "ref": "master" }' \
          --url 'https://api.github.com/repos/cuvidk/os-setup/actions/workflows/update.yml/dispatches'
